Decode morse
rivasbolinga/morse-code pull request #1
Opened 2023-07-19 18:35 UTC by danielsafari143

In this pull request, we were able to : 
- Run a program using the command line.
- Use Ruby syntax for basic programming operations.
- Create a method to decode a Morse code character.
- Create a method to decode an entire word in Morse code.
- Create a method to decode the entire message in Morse code.

2023-07-19 19:30 UTC, Lucas-Masaba requested changes
# Hello @danielsafari143 👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Well-written pull request description :writing_hand: 
- The Morse code functionality is working as expected :gear: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 19:30 UTC, Lucas-Masaba commented on README.md
> +  npm install
- [ ] We do not need the `npm install` command when setting this project up locally. Please remove this to make your documentation professional and less confusing to a user :+1:

2023-07-19 19:45 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @danielsafari143 & @rivasbolinga, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Application works as expected :white_check_mark: 
- [x] Application is modular as required in project requirements :white_check_mark: 
- [x] Pull request has a descriptive summary and title :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 19:48 UTC, rivasbolinga commented on README.md
> +  npm install
Hi @Lucas-Masaba ! Thanks for your review. We have deleted the line from the README file as you indicated. However I still have a question. 
  What about` npm install` to install the linters since the potential user doesn't know what linters we used? 
Regards

2023-07-19 19:48 UTC, merged

2023-07-19 22:30 UTC, Felix45 commented on README.md
> +  npm install
Hi @rivasbolinga the `npm install` command is usually used to install dependencies in projects that use modules from node packages, this project is a `ruby` based project and does not rely on any dependency from the node package manager that's why you don't need to include the `npm install` command on your readme file.

2023-07-20 23:11 UTC, Lucas-Masaba commented on README.md
> +  npm install
Hello @rivasbolinga , sorry for the late reply but I'm glad @Felix45 shared the right answer. I'm also glad it helped. Happy coding :man_technologist: